services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/api
    depends_on:
      - db

  db:
    image: postgres:17.4
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
